#ifndef PCH_H
#define PCH_H

#include <map>
#include <string>
#include <vector>
#include <functional>
#include <algorithm>
#include <string>
#include <iostream>
#define _USE_MATH_DEFINES
#include <cmath>
#include <list>
#include <sstream>
#include <iostream>
#include <fstream>
#include <cstdio>
#include <cassert>
#include <stack>
#include <iterator>
#include <random>
#include <thread>
#include <chrono>
#include <mutex>
#endif //PCH_H
